<?php
declare(strict_types=1);

// Disney SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DisneyUtility::setRegistrar(function (DisneyUtility $u): void {
    $u->clean = [DisneyClean::class, 'call'];
    $u->done = [DisneyDone::class, 'call'];
    $u->make_error = [DisneyMakeError::class, 'call'];
    $u->feature_add = [DisneyFeatureAdd::class, 'call'];
    $u->feature_hook = [DisneyFeatureHook::class, 'call'];
    $u->feature_init = [DisneyFeatureInit::class, 'call'];
    $u->fetcher = [DisneyFetcher::class, 'call'];
    $u->make_fetch_def = [DisneyMakeFetchDef::class, 'call'];
    $u->make_context = [DisneyMakeContext::class, 'call'];
    $u->make_options = [DisneyMakeOptions::class, 'call'];
    $u->make_request = [DisneyMakeRequest::class, 'call'];
    $u->make_response = [DisneyMakeResponse::class, 'call'];
    $u->make_result = [DisneyMakeResult::class, 'call'];
    $u->make_point = [DisneyMakePoint::class, 'call'];
    $u->make_spec = [DisneyMakeSpec::class, 'call'];
    $u->make_url = [DisneyMakeUrl::class, 'call'];
    $u->param = [DisneyParam::class, 'call'];
    $u->prepare_auth = [DisneyPrepareAuth::class, 'call'];
    $u->prepare_body = [DisneyPrepareBody::class, 'call'];
    $u->prepare_headers = [DisneyPrepareHeaders::class, 'call'];
    $u->prepare_method = [DisneyPrepareMethod::class, 'call'];
    $u->prepare_params = [DisneyPrepareParams::class, 'call'];
    $u->prepare_path = [DisneyPreparePath::class, 'call'];
    $u->prepare_query = [DisneyPrepareQuery::class, 'call'];
    $u->graphql_body = [DisneyGraphql::class, 'body'];
    $u->graphql_errors = [DisneyGraphql::class, 'errors'];
    $u->result_basic = [DisneyResultBasic::class, 'call'];
    $u->result_body = [DisneyResultBody::class, 'call'];
    $u->result_headers = [DisneyResultHeaders::class, 'call'];
    $u->transform_request = [DisneyTransformRequest::class, 'call'];
    $u->transform_response = [DisneyTransformResponse::class, 'call'];
});
